[package]
name = "hyper-text-stitcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_parser = "0.7.0"
rhai = "1.17.1"
clap = "4.5.2"